### ISSUE TITLE
Input folder fields are readonly

### ISSUE THREAD

**Issue by PySimpleGUI** [driverxxvii/PDF_Tools#2]
Any particular reason the folder fields are readonly?

I never press a browse button in PySimpleGUI.  I always just paste in the filename / foldername into the input element.

**Comment by driverxxvii** [comment]
> I never press a browse button in PySimpleGUI. I always just paste in the filename / foldername into the input element.

Good point. I usually click browse and then paste into the file name field.

>Any particular reason the folder fields are readonly?

It was really a cop out way to avoid checking if the folder path supplied is valid. This is something that could go on my todo list.
I am adding a gui around another program I made sometime back and have incorporated checks to make sure that file selected is valid and so on (using things like pathlib.path.isfile() etc)

On a different note, on one of your videos I saw that you right clicked a file on your desktop and selected "path to file", which copied the path to your clipboard. Are you using a special program to do that or are you using linux or something?

Again, thanks for the feedback.

**Comment by PySimpleGUI** [comment]
I use a program called QTTab Browser

It adds TABS to explorer!  My Explorer looks like this...

![image](https://user-images.githubusercontent.com/46163555/83421409-0d618a80-a3f6-11ea-89d5-d2e1d9cf5c2b.png)


One "key binding" it has is "Copy as path".  I press Control+Shift+C and instead of copying the file, it copies the path to the file.

If you right click a filename in explorer, you'll see an entry called "Copy as path" that does this same thing.

![image](https://user-images.githubusercontent.com/46163555/83421523-3b46cf00-a3f6-11ea-945b-cf003e3416ba.png)

I use this hotkey combination 100's of times a day.  It should be part of windows. 

Find a way to make this binding work for you.  Find a way to assign Shift+Control+c or something that simple into copying the path.

I combine this with programs like yours.  I copy the path to a file, then I simply paste into the input field.

**Comment by driverxxvii** [comment]
I wondered why your windows looked that way. Will take a look at it.

When I saw you right click and select copy as path, I tried it and couldn't find it in the menu. So I assumed that it isn't part of normal  windows.
It turns out that you need to hold shift and right click for that menu item to appear. I don't know why they would hide something so useful. I've been going into the explorer address bar each time to copy the folder location.

**Comment by driverxxvii** [comment]
Fixed this and added checks to make sure the path selected is valid.
