### ISSUE TITLE
Popup / message on complete

### ISSUE THREAD

**Issue by PySimpleGUI** [driverxxvii/PDF_Tools#3]
After pressing Create PDF button, I have no idea as to the progress and if/when it completes.

There are a LOT of ways to show the user that you're done:

* You can show it in the window itself with a status text element that changes - blank, processing, done
* Show a plain blocking popup at the end (keep on top set)
* Show an auto-close popup
* Show a "quick message" (again, keep on top so that it's not lost)
* Show a progress bar / use the single-line-progress-meter - this may happen super quickly.  Some of my programs use this but users rarely see it... the convert images to Base64 is an example of something like this I think.

Otherwise I just don't know as a user when something's completed.

**Comment by driverxxvii** [comment]
Will update to include this. I used the one-line-progress-meter on a different program (resizing down images). 
For this one I think I'll go with a pop or message on the gui.
