### ISSUE TITLE
PEP8 bindings

### ISSUE THREAD

**Issue by PySimpleGUI** [driverxxvii/PDF_Tools#4]
Where did you learn to code PySimpleGUI?

Your coding conventions are very very old and no longer used.  

ChangLookAndFeel is now theme

.Layout isn't used anywhere

All names have PEP8 versions.   `window.Read()` was replaced by `window.read()`

A LOT of time has been spent changing all of the documentation and all of the demo programs to reflect the new coding conventions. I'm trying very hard to "stamp out" any locations that are teaching the old way.

Did you see the old videos?  If so, they need to come down from YouTube.

Example:

```python
    return sg.Window("Images to PDF").Layout(layout)
```

is now

```python
    return sg.Window("Images to PDF", layout)
```

**Comment by driverxxvii** [comment]
I came across a comment you had made, either on reddit or stackoverflow and that's when I started using PySimpleGUI. When did you release it publicly? I can't quite remember when I first tried it.

Sometime back I made a pysimplegui template 
```
import PySimpleGUI as sg


def gui_layout():
    layout = [
        [sg.Button("Click Me", key="Click"),
         sg.VerticalSeparator()],
        [sg.Button("OK")]
    ]

    return sg.Window("window title", layout=layout)


def event_loop():
    window = gui_layout()

    while True:
        event, values = window.read(100)
        print("read")

        if event in (None, "Exit"):
            break

        if event == "Click":
            pass


event_loop()
```
I've been modifying it as I find the new ways of doing things. I don't use the .Layout anymore, I must have forgotten to change it on this one.
Also, I just figured out reading the docs again what the window.read(timeout) option is and that I don't need it. I vaguely remember that it used to be something like readnonblocking or something.

I also stumbled upon this bit at the end of your pysimplegui.py

```
# ------------------------ PEP8-ify The SDK ------------------------#

change_look_and_feel = ChangeLookAndFeel
convert_args_to_single_string = ConvertArgsToSingleString
convert_flex_to_tk = ConvertFlexToTK
easy_print = EasyPrint
easy_print_close = EasyPrintClose
```
So I presumed that you are trying to rewrite some things to conform to pep8.
